version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: "convert_test_redis"
    command: redis-server --save ""
    ports:
      - "6380:6379"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
